### PR TITLE
fix: package control can be an optional dependency

### PR DESCRIPTION
**Pull request by gerardroche**
This change refactors the package control dependency to be optional by catching the import error if package control is not available and making it an no-op operation.

Previously the import error at the top prevented LSP utils from working properly when package control was not available.

### CODE REVIEW

**Comment by predragnikolic** [comment]
In order for lsp_utils to be installed, PC must exist. Because PC manages dependencies.

In what scenario will the user not have PC installed?

**Comment by gerardroche** [comment]
I have the dependencies manually installed.

**Comment by predragnikolic** [comment]
Just to conclude, you don't want to be dependent on package control?

**Comment by gerardroche** [comment]
Yes. Maybe. I thought it was going to be too difficult to install things without package control. I'm surprised how easy it is. The Sublime Text packages system out of the box is very smart.

Some language servers like phpactor worked straight away (they don't depend on `lsp_utils`), others wouldn't because the exception is raised at load time. Otherwise everything seems to be working.

As far as I can tell this is the only reference to package control.

Plugins that depend on pc typically wrap related code in a try except block, but feel free to rework the pr.

- https://github.com/SublimeLinter/SublimeLinter/blob/master/sublime_linter.py#L52
- https://github.com/NeoVintageous/NeoVintageous/blob/master/plugin.py#L174

**Pull request merged**
