### PR TITLE
Expose "ready" property for checking if server installed successfully

### PR DESCRIPTION
**Pull request by rchl**
The idea is to then have a check like this one in `def config`  in LSP-* packages:
```py
        if not server.ready:
            return read_client_config(self.name, {
                'enabled': False,
                'languages': [{}],
            })
```

### CODE REVIEW

**Comment by rchl** [comment]
Actually this won't work that well as once LSP gets such configuration, it will consider client disabled for session so restart would be necessary.

Would probably need some bigger refactoring to get this working as expected.

@rwols FYI

**Comment by rwols** [comment]
The way to solve this for now IMO is to just run the code in the main thread, not in a separate thread.

With asyncio we could make this non-blocking, but that's a story for later.

**Comment by rchl** [comment]
No, sorry, I'd rather live with current (minor) problem as blocking the main thread would give a horrible user experience (especially with bigger servers like lsp-vue).

**Comment by rwols** [comment]
Sure :)

**Comment by rchl** [comment]
Actually still gonna go with this change as we can instead bailout in `on_start` override, based on `server.ready`.

**Comment by predragnikolic** [comment]
Your intent is to use the `.ready` boolean in the `on_start` method of a LanguageHandler
to not start the LanguageHandler if the server is not ready. Is that right?

**Comment by rchl** [comment]
> Your intent is to use the `.ready` boolean in the `on_start` method of a LanguageHandler
> to not start the LanguageHandler if the server is not ready. Is that right?

Correct

**Comment by predragnikolic** [comment]
Can we make a release now? :)

**Comment by rchl** [comment]
Sure :)

**Comment by rchl** [comment]
1.1.0 released

**Pull request merged**
