### PR TITLE
Add support for specifying minimum Node version

### PR DESCRIPTION
**Pull request by rchl**
A plugin can define a class method like:

@classmethod
def minimum_node_version(cls) -> Tuple[int, int, int]:
    return (10, 0, 0)

to specify the minimum Node version required by the server. By default
the minimum is v8.

Relates to https://github.com/sublimelsp/LSP-pyright/issues/15

### CODE REVIEW

**Comment by rchl** [comment]
@AmjadHD

**Comment by rwols** [comment]
Pretty handy. I think we can generalize this to all plugins in some way.

**Comment by rchl** [comment]
I guess pip comes to mind with its "requirements". But I can't easily see a generic solution to handle both.

For this use case we need to:
 - run command (`node --version`)
 - parse the version output
 - compare with minimum version that is hardcoded

How could this be handled in a declarative way? And how would be required for `pip`? And what would be a generic name for of such method?

**Comment by rwols** [comment]
> How could this be handled in a declarative way?

We can add a new method to `AbstractPlugin` that asks for the global requirements. By default it can have no global requirements:

```python
class AbstractRequirement(metaclass=ABCMeta):

    @abstractmethod
    def satisfied(self) -> Optional[str]:
        """Return None if the requirement is satisfied, otherwise return an explanation of the failing requirement"""
        pass


class NodeRequirement(AbstractRequirement):

    def __init__(self, min_version: Tuple[int, int, int]) -> None:
        ...

    def satisfied(self) -> Optional[str]:
        if self.node_is_missing():
            return "node is not in $PATH"
        elif self.node_version_is_too_low():
            return "node required version is at least X.Y.Z. You have version A.B.C"
        else:
            return None


class AbstractPlugin:

    @classmethod
    def global_requirements(cls) -> Optional[List[AbstractRequirement]]:
        return None

class NodeBasedPlugin(AbstractPlugin):

    @classmethod
    def global_requirements(cls) -> Optional[List[AbstractRequirement]]:
        return [NodeRequirement(12, 0, 0)]
```

**Pull request merged**
